AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter email address")]
        [Display(Name ="Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$",ErrorMessage ="Please enter correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter message")]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using System.Net.Mail;
using Umbraco.Core.Models;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            // returnerer partialview contactfrom.cshtml
            return PartialView("ContactForm", new ContactForm());
        }

        // denne method bliver kørt når du trykker på submit button i form 
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            // tjekker om contactfrom er valid
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            // standard smtp mail function 
            MailMessage message = new MailMessage();
            message.To.Add("elvermikkel9@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("elvermikkel9@gmail.com", "luoerhhuklyzgtvv");
                // send mail   
                smtp.Send(message);
            }

            //sætter min variable tempdata til true fra standard er den null
            TempData["success"] = true;

            // bruger content service api til gemme inputfelter ned i parameter
            IContent msg = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "message");
            msg.SetValue("messageName",model.Name);
            msg.SetValue("email",model.Email);
            msg.SetValue("subject",model.Subject);
            msg.SetValue("messageContent",model.Message);

            // gemmer besked ned i database så den kan ses i backoffice
            Services.ContentService.Save(msg);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

<head>
    <Title>@Umbraco.Field("siteTitle")</Title>
    
    <meta name="description" content="@Umbraco.Field("metaDescription")">
    <meta name="keywords" content="@Umbraco.Field("metaKeywords")">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato:700i" rel="stylesheet"> 
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <script src="scripts/bootstrap.min.js"></script>
    <script src="scripts/jquery-3.3.1.min.js"></script>
</head>
<body>
    
    <header class="wrapper clearfix">
        <div class="header">
            @{
                var image = Umbraco.TypedMedia(@Umbraco.Field("logo", recursive: true).ToString());
                <img src="@image.Url" class="header-img" alt="logo"/>
            }
            <h1 class="h1">@Umbraco.Field("siteTitle", recursive: true)</h1>
        </div>
    
        @Umbraco.RenderMacro("MainMenu")
        
    </header>
    <div class="center bottom">
        @Html.GetGridHtml(@Model, "myGrid", "Bootstrap3-Fluid")
    </div>
    
    <footer class="container-fluid bg-primary cos-footer">
        <p>&copy @Umbraco.Field("footer", recursive: true)</p>
    </footer>
    
</body>

AarhusWebDevCoop/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="center">
    <h2>@Model.ArticleTitle</h2>
    <p>@Model.ArticleContent</p>
</div>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="center">
    <h2>@Model.ArticlesTitle</h2>
    <p>@Model.ArticlesBodyText</p>
    @Umbraco.RenderMacro("list")
</div>

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="contact-center">
    <h2>Contact Us</h2>
    @Html.Action("Index", "ContactFormSurface")
</div>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
    
    <div>
        <div class="row">
            <p>@Model.MainContent</p>
        </div>
        
        <div class="row">
            <div class="col-6">
                <h3>News</h3>
                @Umbraco.RenderMacro("listnews")
            </div>
        
            <div class="col-6">
                <h3>Project</h3>
                @Umbraco.RenderMacro("listNewestProjects", new {numOfProjects="5"})
            </div>
        </div>
    </div>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
    @Html.Partial("LoginForm")

AarhusWebDevCoop/Views/MacroPartials/MainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the CSS class "current".
*@
@{ 
    @* opretter 2 variabler en som har sidens root den anden ligger alle undersider i et array *@
    var root = Model.Content.Site();
    var selection = root.Children.Where(x => x.IsVisible()).ToArray(); 
}

@if (selection.Length > 0)
{
<nav class="navbar navbar-expand-lg navbar-dark bg-primary nav-pos">
<div class="center">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        @* hard koder Root menupunkt *@
        <li class="nav-item @(Model.Content.Level == 1 ? "active" : null)">
            <a class="nav-link" href="@root.Url">@root.Name</a>
        </li>
        
        @* dette foreach looper alle undersider igennem*@
        @foreach (var item in selection)
        {
            @* li for klassen active vis man er inde på en parrent eller underside til parrent *@
            <li class="nav-item @(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
            @* min if kikker på om menupunkt er login og om der er logget nogen bruger ind vis begge
            disse krav er opfyldt laver den min login om til profile i sted*@
            @if (item.Name == "Login" && Members.GetCurrentLoginStatus().IsLoggedIn) {
                <a class="nav-link" href="@item.Url">Profile</a>
            }@* denne else if skifter mit projects menupunkt ud med min projects dropdown *@
            else if (item.Name == "Projects") {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Projects
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @* bruger min dropdown marco som lister alle undersider fra project overview *@
                        @Umbraco.RenderMacro("dropDownLost")
                    </div>
                </li>
                
            } @* else tilføjer bare de normale undersider *@
            else {
                <a class="nav-link" href="@item.Url">@item.Name</a>
            }
            </li>
        }
        
        
    </ul>
  </div>
  @* vis man er logged ind kommer der en lille box over i højre side af menu *@
  @if(Members.GetCurrentLoginStatus().IsLoggedIn){
    <div class="menu-login row">
        @* skriver uf hvem der er logged ind *@
        <p class="p">Hello @Members.GetCurrentLoginStatus().Name</p>
        @* laver et redirect variable to min root *@
        @{
            var logoutModel = new PostRedirectModel();
            logoutModel.RedirectUrl = "/";
        }
        @* når man trykker på logud knappen køre min logincontroller logger den dig ud og redirecter dig til den skrevet redirect *@
        @using(Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout")) {
        <button class="btn btn-danger fr logout">Logout</button>
        @Html.HiddenFor(m => logoutModel.RedirectUrl)
        }
        <p style="clear:both;"></p>
    </div>
  }
  
  
    
    
  
</div>
</nav>
}

AarhusWebDevCoop/Views/MacroPartials/Sitemap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Core.Models
@using Umbraco.Web


@*
    This snippet makes a list of links of all visible pages of the site, as nested unordered HTML lists.

    How it works:
    - It uses a custom Razor helper called Traverse() to select and display the markup and links.
*@

@{ var selection = Model.Content.Site(); }

<div class="sitemap">
    @* Render the sitemap by passing the root node to the traverse helper, below *@
    <ul class="sitemap lower">
        <li class="level-1">
            <strong><a href="/">Home</a></strong>
        </li>
    </ul>
    @Traverse(selection)
</div>


@* Helper method to traverse through all descendants *@
@helper Traverse(IPublishedContent node)
{
    @* Update the level to reflect how deep you want the sitemap to go *@
    const int maxLevelForSitemap = 4;

    @* Select visible children *@
    var selection = node.Children.Where(x => x.IsVisible() && x.Level <= maxLevelForSitemap).ToArray();

    @* If any items are returned, render a list *@
    if (selection.Length > 0)
    {
        <ul class="sitemap">
            @foreach (var item in selection)
            {
                if(item.Name != "Site map")
                {
                    <li class="level-@item.Level">
                        @if (item.Level > 2) {
                            <a href="@item.Url">@item.Name</a>

                            @* Run the traverse helper again for any child pages *@
                            @Traverse(item)
                        } else {
                            <strong><a href="@item.Url">@item.Name</a></strong>

                            @* Run the traverse helper again for any child pages *@
                            @Traverse(item)
                        }
                    </li>
                }
                
            }
        </ul>
    }
}

AarhusWebDevCoop/Views/MacroPartials/drop-down lost.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then uses the OrderByDescending() method, which takes the property to sort. In this case the page's creation date.
    - It then generates links so the visitor can go to each page
*@

@{ 
    var selection =  Model.Content.Site().Children
                .Where(x => x.DocumentTypeAlias == "projectOverview")
                .First()
                .Children
                .OrderByDescending(x => x.CreateDate)
                .Where(x => x.IsVisible())
                .ToArray();
}



@if (selection.Length > 0)
{
    foreach (var item in selection)
    {
        var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
        var loginAccess = isProtected && umbraco.library.HasAccess(item.Id, item.Path);
        
        if(!isProtected || loginAccess){
            <a class="dropdown-item" href="@item.Url">@item.Name</a>
        }
    }
}

AarhusWebDevCoop/Views/MacroPartials/list.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then generates links so the visitor can go to each page
*@

@{ var selection = Model.Content.Children.ToArray(); }

@if (selection.Length > 0)
{
    <div class="list-group">
        @foreach (var item in selection)
        {
            <a href="@item.Url" class="list-group-item list-group-item-action col-6">@item.Name</a>
        }
    </div>
}

AarhusWebDevCoop/Views/MacroPartials/listNewestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then uses the OrderByDescending() method, which takes the property to sort. In this case the page's creation date.
    - It then generates links so the visitor can go to each page
*@

@{ 
    int numOfProjects = Convert.ToUInt16(Model.MacroParameters["numOfProjects"]);
    var selection =  Model.Content.Children
                .Where(x => x.DocumentTypeAlias == "projectOverview")
                .First()
                .Children
                .Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed")
                .Take(numOfProjects)
                .ToArray();
}

@if (selection.Length > 0)
{
    <div class="list-group">
        @foreach (var item in selection)
        {
            <a href="@item.Url" class="list-group-item list-group-item-action">@item.Name</a>
        }
    </div>
}

AarhusWebDevCoop/Views/MacroPartials/listnews.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    Macro to list all child pages under a specific page in the content tree.

    How it works:
        - Confirm the startNodeId macro parameter has been passed in with a value
        - Loop through all child pages
        - Display a list of link to those pages, sorted by the value of the propertyAlias

    Macro Parameters To Create, for this macro to work:
    Alias:startNodeId     Name:Select starting page    Type:Content Picker
*@

@{ 
    var startNodeId = 1090;
}

@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.TypedContent(startNodeId);
    var selection = startNode.Children.Where(x => x.IsVisible()).Take(3).ToArray();

    if (selection.Length > 0)
    {
        <div class="list-group">
            @foreach (var item in selection)
            {
                <a href="@item.Url" class="list-group-item list-group-item-action">@item.Name</a>
            }
        </div>
    }
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Master>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

<!doctype html>
<head>
    <Title>@Umbraco.Field("siteTitle")</Title>

    <meta name="description" content="@Umbraco.Field("metaDescription")">
    <meta name="keywords" content="@Umbraco.Field("metaKeywords")">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato:700i" rel="stylesheet">
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <script src="scripts/bootstrap.min.js"></script>
    <script src="scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>

    <header class="wrapper clearfix">
        <div class="header">
            @{
                var image = Umbraco.TypedMedia(@Umbraco.Field("logo", recursive: true).ToString());
                <img src="@image.Url" class="header-img" alt="logo"/>
            }
            <h1 class="h1">@Umbraco.Field("siteTitle", recursive: true)</h1>
        </div>
        
        @Umbraco.RenderMacro("MainMenu")

    </header>
    <div class="center bottom">
            @RenderBody()
    </div>

    <footer class="container-fluid bg-primary cos-footer">
        <p>&copy @Umbraco.Field("footer", recursive: true)</p>
    </footer>
    @*@Model.Value("footer", fallback: Fallback.ToAncestors)*@
</body>

AarhusWebDevCoop/Views/MemberList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MemberList>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{
	Layout = "Master.cshtml";
    var memberService = ApplicationContext.Current.Services.MemberService;
    var active = memberService.GetMembersByGroup("Active");
    var guest = memberService.GetMembersByGroup("Guest");
}

<h2>Active Members</h2>
<br>
<div class="row">
    
@foreach (var member in active) {
    
    <div class="user row">
        <div class="col-5">  
        @if(member.GetValue("photo") != null) {
            string image = member.GetValue<string>("photo");
            if(image != null) {
            ImageCropDataSet imageCrop = JsonConvert.DeserializeObject<ImageCropDataSet>(image);
            <img src="@imageCrop.Src.GetCropUrl(width: 100)"/>
            }
        }
        </div>
        
        <div class="col-7">  
        <p>@member.Name</p>
        
        @member.GetValue("address")<br>
        @member.GetValue("city")
        @member.GetValue("zip") <br>
        Email: @member.Email<br>
        Skills: 

        @if (member.GetValue("skills") != null)
        {
            string[] skills = member.GetValue("skills").ToString().Split(',');
    
            string skillString = 
            string.Join(", ", from skill in skills 
            select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));
            <span>@skillString</span>
        }
        </div>
    </div>
    <p style="clear:both;"></p>
}
</div>
<br />
<h2>Guest Members</h2>
<br>
<div class="row">
    
@foreach (var member in guest) {
    
    <div class="user row">
        <div class="col-5">  
        @if(member.GetValue("photo") != null) {
            string image = member.GetValue<string>("photo");
            if(image != null) {
            ImageCropDataSet imageCrop = JsonConvert.DeserializeObject<ImageCropDataSet>(image);
            <img src="@imageCrop.Src.GetCropUrl(width: 100)"/>
            }
        }
        </div>
        
        <div class="col-7">  
        <p>@member.Name</p>
        Email: @member.Email
        </div>
    </div>
    <p style="clear:both;"></p>
}
</div>

AarhusWebDevCoop/Views/Partials/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm
@{
    Layout = null;
}
@* vis temp data er null viser den contact form ellers viser den beskeden i else *@
@if(TempData["success"] == null)
{
using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
{
<div class="form-group">
    @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-12">
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-12">
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-12">
        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
        @Html.ValidationMessageFor(m => m.Subject)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-12">
        @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
        @Html.ValidationMessageFor(m => m.Message)
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-12">
        @* på tryk køre methoden HandleFormSubmit *@
        <button id="contact-submit" type="submit" class="btn btn-primary input-medium pullleft ">Send</button>
    </div>
</div>
}
}
else{
<p>Thanks you for contacting us. we'll be in touch soon!</p>
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}